### ISSUE TITLE
Manual copy of cext.pyx required

### ISSUE THREAD

**Issue by jmelcr** [theochem/horton#150]
After installing Horton, I found out that the install script proobably forgets about cpying cext.pyx file. Without it, the whole Horton module cannot be loaded (with module horton.cext missing).

Done on Ubuntu 16.04.

**Comment by matt-chan** [comment]
@tovrstra I don't understand the cythonized setup.py well enough to know where cext.pyx is copied. I thought cython would do it automatically when you defined it in ext_modules. Can you take a look at this please?

**Comment by matt-chan** [comment]
Hi @jmelcr, I did an install of HORTON 2.0.1 on a new copy of Ubuntu 16.04 and didn't get any errors. Can you provide a bit more info about what version of HORTON you're using and also some error messages please?

Thanks!

**Comment by tovrstra** [comment]
I assume something else must be going wrong. The file `cext.pyx` is normally not copied upon installation. It is only used as input by Cython to generate `cext.cpp`, which is then compiled into a Python extension, `cext.so`, which should get copied when installing. If that is not the case, we need to figure out why. 

@jmelcr This is probably a problem related to your local setup because we do regularly test on Ubuntu 16.04 and never ran into this problem before. Can you describe in more detail what is going wrong? Basically we need the following to help you:

1) The steps to reproduce your problem
2) Terminal output when you take these steps
3) Relevant deviations of your Ubuntu install from a vanilla Ubuntu install.

**Comment by jmelcr** [comment]
Hi - just to let you know - I'll get to this once I finish current task... Joe.

**Comment by tovrstra** [comment]
The following could be causing the problem. When running nosetests in the source directory:

    nosetests -v horton

It will try to run the tests with the horton package in the source tree, where the extensions are not present after installation. That may result in the error you got. There are two ways to fix this:

1) Change to another directory before running the tests: `cd ~; nosetests -v horton`
2) First build the extension in the source tree and then run the tests: `./setup.py build_ext -i; nosetests -v horton`.

Can you try if this helps? Thanks.

**Comment by jmelcr** [comment]
Sorry that I'm lagging. I'l try what you suggest Asap. Joe.

**Comment by jmelcr** [comment]
Hi, here is the result

1) Failed with 8 errors
2) OK (in the source directory)
+
3) after build_ext I ran nosetests somewhere else: Fails with same errors as in 1)
logs attached: [nosetests-horton.zip](https://github.com/theochem/horton/files/498176/nosetests-horton.zip)

**Comment by tovrstra** [comment]
Thanks for trying this all out. The errors you get are due to files of an older HORTON installation that are still present. Even if you install a newer version of HORTON in the same place, the old one is not automatically removed first. You can fix this as follows, with care though: remove the following files and directories:

    ${HOME}/.local/bin/horton-*.py
    ${HOME}/.local/lib/python2.7/site-packages/horton
    ${HOME}/.local/share/horton

Then install HORTON again and the tests (outside the source tree) should also pass.

Is this the same problem as in #151?

**Comment by jmelcr** [comment]
Thanks, I'll try it. 
Sorry for making a mess here - I probably combined the two issues (this and 151) into this single thread. So, yes, the nosetests report the same errors as in #151 .

**Comment by tovrstra** [comment]
No worries. Bugs are inherently confusing. I'll close #151 then and we'll continue our discussion here.

**Comment by jmelcr** [comment]
I deleted the old installed version of Horton,
updated to nowadays version of Horton (commit 67fc76233bb8ef26ffaee19a37f6b8530d32d683)
and built and nose-tested successfully. 
Thanks,
Joe.

**Comment by tovrstra** [comment]
Thanks for letting use know.
