### ISSUE TITLE
Logging needs to be cleaned up and made consistent

### ISSUE THREAD

**Issue by matt-chan** [theochem/horton#54]
The timer right now lives as long as the python interpreter lives. 

It would be useful to be able to start/stop/reset the timer, in case someone wants to put Horton as a part of a larger script, or run multiple jobs in one interpreter.

**Comment by tovrstra** [comment]
Sounds good. I guess, there should also be a feature then to print the timer output before resetting the timer. Now that is only done when exiting the interpreter.

**Comment by tovrstra** [comment]
There is already a reset method: `timer.reset()` will do it. There are a few other points that to be fixed in `horton.log` though. I've renamed this issue accordingly.

**API preserving**

- The reset method is not done very well. It just sets all numbers to zero. It would be better to remove all SubTimer objects entirely. With the current code, you would get a lot of zero CPU times for parts of the code that are not used when the report is generated for the second time (after an earlier reset).

- A reset method should be added to the Biblio object.

**API removing**

- The memory logger is fairly not doing much useful. Certainly with our plans to ditch the Matrix classes, it will become disfunctional. I did not document it as I'd prefer to remove it.

**API breaking**

- There is related commented code in TimerGroup.report, which should be removed.

- We should treat timer and biblio at the same level, i.e. have biblio.cite instead of log.cite. That way, things are more consistent and there is less redundant code. (The _print_references and cite methods of ScreenLog can then be removed.)

- The method log of the class Biblio should be renamed to report for consistency with TimerGroup.
