### ISSUE TITLE
Move QA scripts to separate repository

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#69]
We should make the QA framework reusable in other projects. The current scripts are loosely integrated with HORTON and they can be factored out relatively easily. This would also improve the quality of the QA scripts, because they get used in different scenario's.

Integration or updating of the QA scripts with a new project should work with a bootstrap script, e.g. as follows:

```
wget https://raw.githubusercontent.com/foo/qascripts/bootstrap.sh && bash ./bootstratp.sh
```

The other option is that we work with a git submodule: https://git-scm.com/book/en/v2/Git-Tools-Submodules. I'm generally not a fan of submodules but this may be a good fit because every project then has the freedom to make local modifications and rebase these regularly on the developments in the main qascripts repo. (That is different from a conventional dependency where all changes are done upstream.)

The following points should then also be addressed:
- Make some scripts more flexible, e.g. to run only a selection of trapdoor scripts.
- Rewrite some or even all shell scripts ( e.g. `test_all_*.sh`) in Python to keep them maintainable while adding extra features.
- Make a `trapdoor.cfg.example` and add `trapdoor.cfg` to `.gitignore`
- Make better use of `dependencies.txt` when installing/updating stuff.
- Make standard module for reading and using `dependencies.txt`, e.g. including check for duplicate entries.
- Break up checklist in different sections that can be easily referred to from other projects.

**Comment by matt-chan** [comment]
Maybe it makes more sense to make a package out of the QA scripts. That way, we can install them consistently on the docker instances. It's not hard to package them into a (local) rpm for that purpose.

**Comment by kimt33** [comment]
@matt-chan has implemented the QA template code in QuantumElephant/InspectorElephant and I have been using it with submodules. Every time I change some part of the QA code, I have to make a pull request to the respective repo, have that repo merge my commit, and have everyone recursively update the submodule. There's also the problem of which repo we should use, since QuantumElephant/InspectorElephant is only supposed to be a template and not a hub for all QA's that we write for each of our packages. It is also odd to have it separated out from QuantumElephant (especially into our public github repo) if we are developing within QuantumElephant (or theochem). It would be crazy to make a new repo within the organization for each QA fork.

I think subtree would work pretty nicely (https://www.atlassian.com/blog/git/git-submodules-workflows-tips), especially for the QA code. Since we don't need to push back up to the InspectorElephant repo, we don't have to worry about the submodule and whether people have pulled the submodules or not. It will also be easier to modify and update and organize.

**Comment by tovrstra** [comment]
We're currently settling for the cardboardlinter, see https://github.com/theochem/cardboardlint Further comments/thoughts can be posted as issues there.
