### ISSUE TITLE
The elephant must lose some weight (testing must become faster)

### ISSUE THREAD

**Issue by tovrstra** [theochem/horton#94]
- Remove geminals
- Remove Hirshfeld-E

**Comment by sfias** [comment]
When installing HORTON on my Raspberry pi 2B the geminal tests didn't run because it only has 1GB RAM. I noticed test_1dm_ap1rog uses a cc-pvdz basis, which to me seemed a bit large for testing, so I changed it to 3-21g. This makes it run a bit faster and uses less memory. I don't know if you really need d-functions to test ap1rog, maybe the geminal-experts can clarify this... 
I also deleted some of the horton.test.test_examples.test_example_ap1rog_xxx tests using cc-pvdz and aug-cc-pvdz on the Raspberry. Maybe this is something to think about instead of removing all tests completely... If you want I can share the commit...

**Comment by matt-chan** [comment]
I think the plan is to deprecate the old geminals implementation soon, so the testing will become faster that way...

Matt

**Comment by PaulWAyers** [comment]
We can think about using different basis sets too. Geminals is a "static correlation method" so the d-functions are useful mainly because they make convergence a bit trickier. But for testing the code (not the method) a small (even minimal) basis can work I think. Also, we could use a Hubbard model example as the test. I'll let the the gemini decide what's the best test going forward, though.

**Comment by tovrstra** [comment]
The plan is to drop the current implementation soon after making the 2.0.1 release, which will also _solve_ the problems you have now on the Pi. For unit testing, small basis sets are fine. Methods testing also matters but should not be done in unit tests. Regression testing is better for that purpose. I've outlined some ideas for regression testing in issue #70.

**Comment by tovrstra** [comment]
Some other elements that should go (because useless/buggy):
- The `--greedy` option of `horton-wpart.py and `horton-cpart.py`
- `horton-cpart.py` and code that is only is present to make it "work".

**Comment by tovrstra** [comment]
See also #113. For now, I don't see any other parts that are not worth maintaining, so I'll close this

@sfias: Afther this liposection, HORTON tests should run also on the Pi.
